name = "ManifoldExamples"
uuid = "21be47e3-92bf-4199-8515-27870869dcc6"
authors = ["Ronny Bergmann <git@ronnybergmann.net>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
