name = "ManifoldExamples"
uuid = "21be47e3-92bf-4199-8515-27870869dcc6"
authors = ["Ronny Bergmann <git@ronnybergmann.net>", "Mateusz Baran <mateuszbaran89@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ManifoldDiff = "af67fdf4-a580-4b9f-bbec-742ef357defd"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"

[compat]
ManifoldDiff = "0.4"
Manifolds = "0.10"
julia = "1.10"

[targets]
test = ["Test"]
